
echo "I'm running bud!"
echo "changing telcel to vodafone in the APN's"
sed -i -e "s/telcel/vodafone/g" TELCEL.STD_USER.*.csv
echo "APN change complete now splitting ctrl plane and user plane files"
cat TELCEL.STD_CTRL.* >> Control
#split -dl 100000 TELCEL.STD_CTRL.*.csv ctrl_a;
split -dl 100000 Control ctrl_a;
split -dl 100000 TELCEL.STD_USER.*.csv user_a;

echo "Renaming files"

for file in ctrl_*;
do
    if [ -f $file ];
    then
	fileword=$(head -n1 $file | cut -f7 -d",");
	ext=".csv"
	prefix="TELCEL.STD_CTRL."
	[ "$file" != "$fileword" ] && $(mv "$file" "$prefix$fileword$ext")
    fi;
done

for file in user_*;
do
    if [ -f $file ];
    then
	fileword=$(head -n1 $file | cut -f8 -d",");
	ext=".csv"
	prefix="TELCEL.STD_USER."
	[ "$file" != "$fileword" ] && $(mv "$file" "$prefix$fileword$ext")
    fi;
done

echo "Now putting in the right headers"
#After renaming


sed -i -e '1i SESSION_TYPE,SESSION_STRING,SEQUENCE_NO,SESSION_CONTINUATION_FLAG,IMEISV,IMSI,MSISDN,STARTTIME,ENDTIME,DURATION,RESPONSE,SOURCE_TYPE,RADIO_ACCESS_TYPE,CLIENT_ADDRESS,CLIENT_PORT,SERVER_ADDRESS,SERVER_PORT,MCC,MNC,LAC,RAC,CISAC,APN,SGSN,GGSN,ASC,SSC,DL_PACKET_COUNT,DL_PACKET_VOLUME,DL_RETRANS_COUNT,DL_OOS_COUNT,DL_ACTIVE_TIME,DL_TEID,UL_PACKET_COUNT,UL_PACKET_VOLUME,UL_RETRANS_COUNT,UL_OOS_COUNT,UL_ACTIVE_TIME,UL_TEID,TRANSPORT_PROTOCOL,APPLICATION,QOS_REQUESTED,QOS_NEGOTIATED,PELEMT1,PELEMT2,PELEMT3,PELEMT4,PELEMT5,PELEMT6,PELEMT7,PELEMT8,PELEMT9,PELEMT10,PELEMT11,PELEMT12,PELEMT13,PELEMT14,PELEMT15,PELEMT16,PELEMT17,PELEMT18,PELEMT19,PELEMT20,PELEMT21,PELEMT22,PELEMT23,PELEMT24' TELCEL.STD_USER*

sed -i -e '1i RECORD_TYPE,IMEISV,IMSI,MSISDN,OTHER_PARTY_NUMBER,DIRECTION,STARTTIME,ENDTIME,DURATION,RESPONSE,RADIO_ACCESS_TYPE,SOURCE_TYPE,SEQUENCE_NO,SESSION_CONTINUATION_FLAG,3GPP_CODE_VALUE_1,3GPP_CODE_TYPE_1,3GPP_CODE_NAME_1,3GPP_CODE_VALUE_2,3GPP_CODE_TYPE_2,3GPP_CODE_NAME_2,3GPP_CODE_VALUE_3,3GPP_CODE_TYPE_3,3GPP_CODE_NAME_3,3GPP_CODE_VALUE_4,3GPP_CODE_TYPE_4,3GPP_CODE_NAME_4,3GPP_CODE_VALUE_5,3GPP_CODE_TYPE_5,3GPP_CODE_NAME_5,3GPP_CODE_VALUE_6,3GPP_CODE_TYPE_6,3GPP_CODE_NAME_6,3GPP_CODE_VALUE_7,3GPP_CODE_TYPE_7,3GPP_CODE_NAME_7,3GPP_CODE_VALUE_8,3GPP_CODE_TYPE_8,3GPP_CODE_NAME_8,3GPP_CODE_VALUE_9,3GPP_CODE_TYPE_9,3GPP_CODE_NAME_9,3GPP_CODE_VALUE_10,3GPP_CODE_TYPE_10,3GPP_CODE_NAME_10,MSC,ROUTE_INCOMING,ROUTE_OUTGOING,INITIAL_CELL_MCC,INITIAL_CELL_MNC,INITIAL_CELL_LAC,INITIAL_CELL_RAC,INITIAL_CELL_CISAC,FINAL_CELL_MCC,FINAL_CELL_MNC,FINAL_CELL_LAC,FINAL_CELL_RAC,FINAL_CELL_CISAC,SMSC,APN,SGSN,GGSN,OPC,DPC,CALLSETUPTIME,PREEMPTED_CALL_FLAG,EMERGENCY_CALL_FLAG,ANSWER_FLAG,SMS_LENGTH,UI_TEID,DL_TEID,DL_VOLUME,UL_VOLUME,IP_ADDRESS,UL_PACKET_COUNT,DL_PACKET_COUNT,UL_RETRANS_COUNT,DL_RETRANS_COUNT,QOS_REQUESTED,QOS_NEGOTIATED' TELCEL.STD_CTRL*


